-- Esquema base para Supabase del sistema de estacionamiento.
-- Incluye tipos, tablas, indices, RLS, triggers y datos semilla iniciales.

begin;

create extension if not exists pgcrypto;

do $$
begin
  create type parking_space_type as enum ('simple', 'doble_fondo', 'doble_frente');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type parking_space_status as enum ('disponible', 'ocupado', 'alerta', 'mantenimiento', 'reservado');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type parking_alert_status as enum ('NUEVO', 'ESCALADA');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type app_role as enum ('guardia', 'jefe_seguridad', 'servicios_generales');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  role app_role not null default 'guardia',
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.parking_spaces (
  id text primary key,
  zone text not null,
  type parking_space_type not null,
  status parking_space_status not null default 'disponible',
  pair_id text unique,
  plate text,
  driver_name text,
  phone text,
  entry_time time,
  maintenance_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint parking_spaces_pair_self_check check (pair_id is null or pair_id <> id)
);

alter table public.parking_spaces
  drop constraint if exists parking_spaces_pair_id_fkey;

alter table public.parking_spaces
  add constraint parking_spaces_pair_id_fkey
  foreign key (pair_id)
  references public.parking_spaces (id)
  on delete set null
  deferrable initially deferred;

create index if not exists parking_spaces_zone_idx on public.parking_spaces (zone);
create index if not exists parking_spaces_status_idx on public.parking_spaces (status);
create index if not exists parking_spaces_type_idx on public.parking_spaces (type);

create table if not exists public.parking_sessions (
  id uuid primary key default gen_random_uuid(),
  space_id text not null references public.parking_spaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  plate text,
  driver_name text,
  phone text,
  zone text not null,
  space_type parking_space_type not null,
  entry_time timestamptz not null default now(),
  exit_time timestamptz,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint parking_sessions_status_check check (status in ('active', 'closed'))
);

create index if not exists parking_sessions_space_id_idx on public.parking_sessions (space_id);
create index if not exists parking_sessions_status_idx on public.parking_sessions (status);
create index if not exists parking_sessions_entry_time_idx on public.parking_sessions (entry_time desc);

create table if not exists public.parking_alerts (
  id bigint generated by default as identity primary key,
  plate text not null,
  blocked_space_id text not null references public.parking_spaces (id) on delete cascade,
  blocker_space_id text not null references public.parking_spaces (id) on delete cascade,
  driver_name text not null,
  phone text not null,
  status parking_alert_status not null default 'NUEVO',
  seconds_remaining integer not null default 300 check (seconds_remaining >= 0),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint parking_alerts_spaces_different check (blocked_space_id <> blocker_space_id)
);

create index if not exists parking_alerts_status_idx on public.parking_alerts (status);
create index if not exists parking_alerts_created_at_idx on public.parking_alerts (created_at desc);

create table if not exists public.parking_activity_log (
  id bigint generated by default as identity primary key,
  space_id text references public.parking_spaces (id) on delete set null,
  session_id uuid references public.parking_sessions (id) on delete set null,
  alert_id bigint references public.parking_alerts (id) on delete set null,
  actor_role app_role,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists parking_activity_log_created_at_idx on public.parking_activity_log (created_at desc);
create index if not exists parking_activity_log_space_id_idx on public.parking_activity_log (space_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_parking_spaces_updated_at on public.parking_spaces;
create trigger trg_parking_spaces_updated_at
before update on public.parking_spaces
for each row execute function public.set_updated_at();

drop trigger if exists trg_parking_sessions_updated_at on public.parking_sessions;
create trigger trg_parking_sessions_updated_at
before update on public.parking_sessions
for each row execute function public.set_updated_at();

drop trigger if exists trg_parking_alerts_updated_at on public.parking_alerts;
create trigger trg_parking_alerts_updated_at
before update on public.parking_alerts
for each row execute function public.set_updated_at();

create or replace function public.sync_session_on_space_change()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'ocupado' then
    if new.entry_time is null then
      new.entry_time = (now() at time zone 'UTC')::time;
    end if;

    if not exists (
      select 1
      from public.parking_sessions
      where space_id = new.id
        and status = 'active'
    ) then
      insert into public.parking_sessions (
        space_id,
        plate,
        driver_name,
        phone,
        zone,
        space_type,
        entry_time,
        status
      )
      values (
        new.id,
        new.plate,
        new.driver_name,
        new.phone,
        new.zone,
        new.type,
        now(),
        'active'
      );
    end if;
  elsif old.status = 'ocupado' and new.status = 'disponible' then
    update public.parking_sessions
      set exit_time = now(),
          status = 'closed'
    where space_id = new.id
      and status = 'active';

    new.plate = null;
    new.driver_name = null;
    new.phone = null;
    new.entry_time = null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_session_on_space_change on public.parking_spaces;
create trigger trg_sync_session_on_space_change
before update on public.parking_spaces
for each row execute function public.sync_session_on_space_change();

alter table public.profiles enable row level security;
alter table public.parking_spaces enable row level security;
alter table public.parking_sessions enable row level security;
alter table public.parking_alerts enable row level security;
alter table public.parking_activity_log enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "spaces_read_authenticated" on public.parking_spaces;
create policy "spaces_read_authenticated"
on public.parking_spaces
for select
to authenticated
using (true);

drop policy if exists "spaces_write_service_role" on public.parking_spaces;
create policy "spaces_write_service_role"
on public.parking_spaces
for all
to service_role
using (true)
with check (true);

drop policy if exists "sessions_read_authenticated" on public.parking_sessions;
create policy "sessions_read_authenticated"
on public.parking_sessions
for select
to authenticated
using (true);

drop policy if exists "sessions_write_service_role" on public.parking_sessions;
create policy "sessions_write_service_role"
on public.parking_sessions
for all
to service_role
using (true)
with check (true);

drop policy if exists "alerts_read_authenticated" on public.parking_alerts;
create policy "alerts_read_authenticated"
on public.parking_alerts
for select
to authenticated
using (true);

drop policy if exists "alerts_write_service_role" on public.parking_alerts;
create policy "alerts_write_service_role"
on public.parking_alerts
for all
to service_role
using (true)
with check (true);

drop policy if exists "activity_read_authenticated" on public.parking_activity_log;
create policy "activity_read_authenticated"
on public.parking_activity_log
for select
to authenticated
using (true);

drop policy if exists "activity_write_service_role" on public.parking_activity_log;
create policy "activity_write_service_role"
on public.parking_activity_log
for all
to service_role
using (true)
with check (true);

-- Seed de usuarios base para que profiles pueda poblarse sin pasos manuales.
insert into auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at
)
select
  seed.id,
  seed.instance_id,
  seed.aud,
  seed.role,
  seed.email,
  seed.encrypted_password,
  seed.email_confirmed_at,
  seed.confirmation_sent_at,
  seed.raw_app_meta_data,
  seed.raw_user_meta_data,
  seed.is_super_admin,
  seed.created_at,
  seed.updated_at
from (
  values
    (
      '11111111-1111-1111-1111-111111111111'::uuid,
      null::uuid,
      'authenticated'::text,
      'authenticated'::text,
      'guardia@duocuc.cl'::text,
      crypt('duocguard1', gen_salt('bf')),
      now(),
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Guardia de Turno"}'::jsonb,
      false,
      now(),
      now()
    ),
    (
      '22222222-2222-2222-2222-222222222222'::uuid,
      null::uuid,
      'authenticated'::text,
      'authenticated'::text,
      'jefe_seguridad@duocuc.cl'::text,
      crypt('duocadmin1', gen_salt('bf')),
      now(),
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Jefe Seguridad"}'::jsonb,
      false,
      now(),
      now()
    ),
    (
      '33333333-3333-3333-3333-333333333333'::uuid,
      null::uuid,
      'authenticated'::text,
      'authenticated'::text,
      'servicios_generales@duocuc.cl'::text,
      crypt('duocadmin1', gen_salt('bf')),
      now(),
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Servicios Generales"}'::jsonb,
      false,
      now(),
      now()
    )
) as seed(
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at
)
where not exists (
  select 1
  from auth.users u
  where u.email = seed.email
);

insert into public.profiles (id, email, full_name, role, phone)
select u.id, u.email,
  case u.email
    when 'guardia@duocuc.cl' then 'Guardia de Turno'
    when 'jefe_seguridad@duocuc.cl' then 'Jefe Seguridad'
    when 'servicios_generales@duocuc.cl' then 'Servicios Generales'
  end,
  case u.email
    when 'guardia@duocuc.cl' then 'guardia'
    when 'jefe_seguridad@duocuc.cl' then 'jefe_seguridad'
    when 'servicios_generales@duocuc.cl' then 'servicios_generales'
  end::app_role,
  case u.email
    when 'guardia@duocuc.cl' then '+56911111111'
    when 'jefe_seguridad@duocuc.cl' then '+56922222222'
    when 'servicios_generales@duocuc.cl' then '+56933333333'
  end
from auth.users u
where u.email in (
  'guardia@duocuc.cl',
  'jefe_seguridad@duocuc.cl',
  'servicios_generales@duocuc.cl'
)
on conflict (id) do update
set email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    phone = excluded.phone,
    updated_at = now();

insert into public.parking_spaces (id, zone, type, status, pair_id, plate, driver_name, phone, entry_time, maintenance_reason)
values
  ('A-01-FONDO',  'A', 'doble_fondo',  'ocupado',       'A-01-FRENTE', 'FRTY-99', 'Ignacio Fuentes', '+56976543210', '11:15', null),
  ('A-01-FRENTE', 'A', 'doble_frente', 'alerta',        'A-01-FONDO',   'BKRT-45', 'Carlos Pérez',    '+56912345678', '12:30', null),
  ('A-02-FONDO',  'A', 'doble_fondo',  'disponible',    'A-02-FRENTE',  null,      null,              null,           null,    null),
  ('A-02-FRENTE', 'A', 'doble_frente', 'disponible',    'A-02-FONDO',   null,      null,              null,           null,    null),
  ('A-03',        'A', 'simple',       'disponible',    null,           null,      null,              null,           null,    null),
  ('A-04',        'A', 'simple',       'ocupado',       null,           'HXDP-41', 'Claudio Miranda', '+56944321155', '13:00', null),
  ('B-01-FONDO',  'B', 'doble_fondo',  'disponible',    'B-01-FRENTE',  null,      null,              null,           null,    null),
  ('B-01-FRENTE', 'B', 'doble_frente', 'disponible',    'B-01-FONDO',   null,      null,              null,           null,    null),
  ('B-02',        'B', 'simple',       'reservado',     null,           null,      null,              null,           null,    null),
  ('B-03',        'B', 'simple',       'mantenimiento', null,           null,      null,              null,           null,    'Restauración de asfalto y pintura de línea'),
  ('C-01-FONDO',  'C', 'doble_fondo',  'disponible',    'C-01-FRENTE',  null,      null,              null,           null,    null),
  ('C-01-FRENTE', 'C', 'doble_frente', 'disponible',    'C-01-FONDO',   null,      null,              null,           null,    null)
  ,('C-02',       'C', 'simple',       'ocupado',       null,           'JPRS-22', 'Esteban Lagos',   '+56922114455', '14:55', null)
on conflict (id) do update
set zone = excluded.zone,
    type = excluded.type,
    status = excluded.status,
    pair_id = excluded.pair_id,
    plate = excluded.plate,
    driver_name = excluded.driver_name,
    phone = excluded.phone,
    entry_time = excluded.entry_time,
    maintenance_reason = excluded.maintenance_reason,
    updated_at = now();

insert into public.parking_sessions (
  id,
  space_id,
  user_id,
  plate,
  driver_name,
  phone,
  zone,
  space_type,
  entry_time,
  exit_time,
  status
)
values
  (
    '44444444-4444-4444-4444-444444444444',
    'A-01-FONDO',
    '11111111-1111-1111-1111-111111111111',
    'FRTY-99',
    'Ignacio Fuentes',
    '+56976543210',
    'A',
    'doble_fondo',
    now() - interval '2 hours',
    null,
    'active'
  ),
  (
    '55555555-5555-5555-5555-555555555555',
    'A-04',
    '22222222-2222-2222-2222-222222222222',
    'HXDP-41',
    'Claudio Miranda',
    '+56944321155',
    'A',
    'simple',
    now() - interval '1 hour 20 minutes',
    null,
    'active'
  ),
  (
    '66666666-6666-6666-6666-666666666666',
    'C-02',
    '33333333-3333-3333-3333-333333333333',
    'JPRS-22',
    'Esteban Lagos',
    '+56922114455',
    'C',
    'simple',
    now() - interval '45 minutes',
    null,
    'active'
  )
on conflict (id) do update
set space_id = excluded.space_id,
    user_id = excluded.user_id,
    plate = excluded.plate,
    driver_name = excluded.driver_name,
    phone = excluded.phone,
    zone = excluded.zone,
    space_type = excluded.space_type,
    entry_time = excluded.entry_time,
    exit_time = excluded.exit_time,
    status = excluded.status,
    updated_at = now();

insert into public.parking_alerts (id, plate, blocked_space_id, blocker_space_id, driver_name, phone, status, seconds_remaining)
values
  (1, 'BKRT-45', 'A-01-FONDO', 'A-01-FRENTE', 'Carlos Pérez', '+56912345678', 'NUEVO', 300),
  (2, 'GHJK-32', 'C-01-FONDO', 'C-01-FRENTE', 'Ana Torres', '+56987654321', 'ESCALADA', 0)
on conflict (id) do update
set plate = excluded.plate,
    blocked_space_id = excluded.blocked_space_id,
    blocker_space_id = excluded.blocker_space_id,
    driver_name = excluded.driver_name,
    phone = excluded.phone,
    status = excluded.status,
    seconds_remaining = excluded.seconds_remaining,
    updated_at = now();

insert into public.parking_activity_log (
  id,
  space_id,
  session_id,
  alert_id,
  actor_role,
  action,
  details,
  created_at
)
values
  (
    1,
    'A-01-FONDO',
    '44444444-4444-4444-4444-444444444444',
    1,
    'guardia',
    'check_in',
    '{"source":"seed","note":"Ingreso de prueba para validar vista de ocupación"}'::jsonb,
    now() - interval '2 hours'
  ),
  (
    2,
    'A-01-FRENTE',
    null,
    1,
    'jefe_seguridad',
    'alert_created',
    '{"source":"seed","note":"Alerta por bloqueo de prueba"}'::jsonb,
    now() - interval '90 minutes'
  ),
  (
    3,
    'C-02',
    '66666666-6666-6666-6666-666666666666',
    2,
    'guardia',
    'check_in',
    '{"source":"seed","note":"Segundo ingreso para probar historial"}'::jsonb,
    now() - interval '45 minutes'
  )
on conflict (id) do update
set space_id = excluded.space_id,
    session_id = excluded.session_id,
    alert_id = excluded.alert_id,
    actor_role = excluded.actor_role,
    action = excluded.action,
    details = excluded.details,
    created_at = excluded.created_at;

commit;